version: '3'

services:
  database:
    image: postgres
    network_mode: bridge2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: papi
    volumes:
    - db-volume:/var/lib/postgresql/data

  api:
    # image: lelesd2m2s10/praticando-api
    image: jgga/praticando-api
    network_mode: bridge2
    environment:
      DB_HOST: database
    ports:
      - "9090:9090"

networks:
  bridge2:
    external: true

volumes:
  db-volume: